--VIEW
/*SCREENER VIEW*/
/*包含其個資和在哪篩檢(都未含地址)*/
CREATE VIEW ALL_SCREENER AS
SELECT CITY.CITY_CODE, CITY_NAME, AREA_CODE, AREA_NAME, PERSON.N_ID, P_NAME, P_AGE, P_GENDER, P_PHONE, P_BIRTH, SCR_DATE, 
	   SCR_RESULT, SCR_PCR_RESULT, SCR_CHRONIC, SCR_TRAVEL, SCREENER.S_ST_ID, S_ST_NAME, S_ST_PHONE, SCREENER.MED_ID, 
	   MED_NAME, MED_PHONE
FROM PERSON RIGHT JOIN SCREENER
ON PERSON.N_ID = SCREENER.N_ID
LEFT JOIN SCREEN_STATION
ON SCREENER.S_ST_ID = SCREEN_STATION.S_ST_ID
LEFT JOIN MEDICAL_INSTITUTION
ON SCREENER.MED_ID = MEDICAL_INSTITUTION.MED_ID
JOIN AREA
ON AREA.AREA_NUM = PERSON.AREA_NUM
JOIN CITY
ON AREA.CITY_CODE = CITY.CITY_CODE;

SELECT *
FROM ALL_SCREENER
ORDER BY CITY_CODE;

/*CONFIRMED VIEW*/
/*包含其個資和在哪隔離(都未含地址)*/
CREATE VIEW ALL_CONFIRMED AS
SELECT CITY.CITY_CODE, CITY_NAME, AREA_CODE, AREA_NAME, PERSON.N_ID, P_NAME, P_AGE, P_GENDER, P_PHONE, P_BIRTH, CASE_NUM, 
	   CON_DATE, CON_ISOLATE_DATE, SCR_CHRONIC, CON_SYMPTOM_DATE, CON_SYMPTOM, CON_STATUS, CONFIRMED.T_P_ID, 
	   T_P_NAME, T_P_PHONE, CONFIRMED.MED_ID, MED_NAME, MED_PHONE
FROM PERSON JOIN CONFIRMED
ON PERSON.N_ID = CONFIRMED.N_ID
LEFT JOIN TREATMENT_PLACE
ON CONFIRMED.T_P_ID = TREATMENT_PLACE.T_P_ID
LEFT JOIN MEDICAL_INSTITUTION
ON CONFIRMED.MED_ID = MEDICAL_INSTITUTION.MED_ID
JOIN AREA
ON PERSON.AREA_NUM = AREA.AREA_NUM
JOIN CITY
ON CITY.CITY_CODE = AREA.CITY_CODE
JOIN SCREENER
ON CONFIRMED.N_ID = SCREENER.N_ID;

SELECT *
FROM ALL_CONFIRMED
ORDER BY CITY_CODE;

/*VACCINE VIEW*/
CREATE VIEW ALL_VACCINE AS
SELECT CITY.CITY_CODE, CITY_NAME, DISTRIBUTE.MED_ID, MED_NAME, MED_PHONE, 
	   DISTRIBUTE.VAC_LOT_NUM, VAC_NAME, DIS_QUANTITY, MANU_NAME, VACCINE.MANU_CODE
FROM DISTRIBUTE JOIN VACCINE
ON DISTRIBUTE.VAC_LOT_NUM = VACCINE.VAC_LOT_NUM
JOIN MANUFACTURER
ON VACCINE.MANU_CODE = MANUFACTURER.MANU_CODE
JOIN MEDICAL_INSTITUTION
ON MEDICAL_INSTITUTION.MED_ID = DISTRIBUTE.MED_ID
JOIN AREA
ON MEDICAL_INSTITUTION.AREA_NUM = AREA.AREA_NUM
JOIN CITY
ON AREA.CITY_CODE = CITY.CITY_CODE;

SELECT *
FROM ALL_VACCINE
ORDER BY CITY_CODE, CAST(SUBSTRING(MED_ID, 2, 3) AS INT);

/*CONFIRMED FOOTPRINT VIEW*/
/*確診者足跡VIEW*/
CREATE VIEW CONFIRMED_FOOTPRINT AS
SELECT FOOTPRINT.N_ID, CASE_NUM, FOOTPRINT.PLACE_ID, F_DATE, F_TIME, PLACE_NAME
FROM ALL_CONFIRMED JOIN FOOTPRINT
ON ALL_CONFIRMED.N_ID = FOOTPRINT.N_ID
JOIN PLACE
ON FOOTPRINT.PLACE_ID = PLACE.PLACE_ID ;

SELECT *
FROM CONFIRMED_FOOTPRINT
ORDER BY CASE_NUM;

/*PEOPLE FOOTPRINT*/
/*所有人的足跡*/
CREATE VIEW PEOPLE_FOOTPRINT AS
SELECT FOOTPRINT.N_ID, FOOTPRINT.PLACE_ID, PLACE_NAME, F_DATE, F_TIME
FROM FOOTPRINT JOIN PLACE
ON FOOTPRINT.PLACE_ID = PLACE.PLACE_ID;

SELECT * 
FROM PEOPLE_FOOTPRINT 
ORDER BY PLACE_ID, F_DATE;


---------------------------------------------------------------------------------------
--QUERY
/*1*/
/*確診且被送至隔離處的人數，排除已過世之人*/
SELECT COUNT(N_ID) AS 'NUM_ISOLATE_PERSON'
FROM ALL_CONFIRMED
WHERE CON_STATUS != '歿';


/*2*/
/*查詢確診者之姓名、年齡、隔離日期、隔離地方之名子及其地址*/
SELECT P_NAME, P_AGE, P_GENDER, P_PHONE, CON_ISOLATE_DATE, T_P_NAME, MED_NAME
FROM ALL_CONFIRMED
WHERE CON_STATUS != '歿';

/*3*/
/*查詢哪些篩檢站之篩檢量 > 平均值，且在那裡篩檢過的人數*/
SELECT S_ST_NAME, S_ST_QUANTITY, COUNT(N_ID) AS 'NUM_of_PEOPLE'
FROM SCREEN_STATION JOIN SCREENER
ON SCREEN_STATION.S_ST_ID = SCREENER.S_ST_ID
GROUP BY S_ST_NAME, S_ST_QUANTITY
HAVING S_ST_QUANTITY > (SELECT AVG(S_ST_QUANTITY) FROM SCREEN_STATION);

/*4*/
/*各縣市的確診人數、篩檢人數*/
SELECT CITY.CITY_NAME, 
	   (SELECT COUNT(N_ID) FROM ALL_CONFIRMED 
		WHERE ALL_CONFIRMED.CITY_CODE = CITY.CITY_CODE) AS 'NUM_of_CONFIRMED',
	   (SELECT COUNT(N_ID) FROM ALL_SCREENER 
		WHERE ALL_SCREENER.CITY_CODE = CITY.CITY_CODE) AS 'NUM_of_SCREENER'
FROM CITY
ORDER BY 'NUM_of_CONFIRMED' DESC;

/*5*/
/*防疫旅館之住房率*/
/*各縣市的總旅館數、總房間數、總空房數、住房率*/
SELECT CITY_NAME, COUNT(EP_HOTEL.T_P_ID) AS 'TOTAL_HOTEL', (SUM(HOTEL_TOTAL_RM)) AS 'TOTAL_RM',
	   (SUM(HOTEL_EMPTY_RM)) AS 'TOTAL_EMPTY_RM',
	   ROUND(((SUM(HOTEL_TOTAL_RM)) - (SUM(HOTEL_EMPTY_RM))) / (SUM(HOTEL_TOTAL_RM)) , 2) AS 'HOTEL_USERAGE'
FROM EP_HOTEL JOIN TREATMENT_PLACE
ON EP_HOTEL.T_P_ID = TREATMENT_PLACE.T_P_ID
JOIN AREA
ON AREA.AREA_NUM = TREATMENT_PLACE.AREA_NUM
JOIN CITY
ON AREA.CITY_CODE = CITY.CITY_CODE
GROUP BY CITY_NAME;

/*6*/
/*各縣市疫苗數*/
/*不分疫苗品種及批號*/
SELECT DISTINCT CITY_NAME, 
	   (SELECT SUM(DIS_QUANTITY) FROM ALL_VACCINE A2 WHERE A1.CITY_CODE = A2.CITY_CODE) AS 'TOTAL_VACCINE'
FROM ALL_VACCINE A1
GROUP BY CITY_NAME, CITY_CODE
ORDER BY 'TOTAL_VACCINE' DESC;

/*7*/
/*各縣市疫苗數、疫苗品牌、疫苗批號*/
/*有分疫苗品種及批號*/
SELECT CITY_NAME, SUM(DIS_QUANTITY) AS 'NUM_of_VACCINE', VAC_NAME, VAC_LOT_NUM
FROM ALL_VACCINE
GROUP BY CITY_NAME, VAC_NAME, VAC_LOT_NUM
ORDER BY CITY_NAME, 'NUM_of_VACCINE' DESC;

/*8*/
/*全台確診者之死亡率*/
/*總確診人數、總確診死亡人數、確診者死亡率*/
SELECT (SELECT COUNT(N_ID) FROM ALL_CONFIRMED) AS 'TOTAL_CONFIRMED', 
	   (SELECT COUNT(N_ID) FROM ALL_CONFIRMED WHERE CON_STATUS = '歿') AS 'DEATH_CONFIRMED',
	   ROUND(CAST((SELECT COUNT(N_ID) FROM ALL_CONFIRMED WHERE CON_STATUS = '歿') AS FLOAT) /
	   CAST((SELECT COUNT(N_ID) FROM ALL_CONFIRMED) AS FLOAT) , 2) AS 'DEATH_PERCENT_CONFIRMED';

/*9*/
/*患有慢性病之死亡率*/
/*患有慢性病且染疫的死亡人數、患有慢性病且染疫的存活人數、患有慢性病的致死率*/
SELECT (SELECT COUNT(N_ID) FROM ALL_CONFIRMED 
		WHERE CON_STATUS = '歿' AND SCR_CHRONIC = '有') AS 'NUM_of_CHRONIC_DEATH',
	   (SELECT COUNT(N_ID) FROM ALL_CONFIRMED 
		WHERE SCR_CHRONIC = '有') AS 'NUM_of_CHRONIC',
		ROUND(CAST((SELECT COUNT(N_ID) FROM ALL_CONFIRMED WHERE CON_STATUS = '歿' AND SCR_CHRONIC = '有') AS FLOAT) /
	    CAST((SELECT COUNT(N_ID) FROM ALL_CONFIRMED WHERE SCR_CHRONIC = '有') AS FLOAT) , 2) AS 'DEATH_PERCENT';

/*10*/
/*全台確診率*/
/*全台總人數、全台有多少人確診、確診率、年紀最小確診者的年齡、年紀最大確診者的年齡、平均確診者之年齡*/
SELECT (SELECT COUNT(N_ID) FROM PERSON) AS 'Total_Person', COUNT(ALL_CONFIRMED.N_ID) AS 'TOTAL_CONFIRMED',
	   ROUND(CAST((SELECT COUNT(ALL_CONFIRMED.N_ID)) AS FLOAT) / 
			 CAST((SELECT COUNT(N_ID) FROM PERSON) AS FLOAT) , 2) AS 'CONFIRMED_PERCENT',
	   MIN(ALL_CONFIRMED.P_AGE) AS 'MIN_AGE_CONFIRMED', MAX(ALL_CONFIRMED.P_AGE) AS 'MAX_AGE_CONFIRMED',
	   AVG(ALL_CONFIRMED.P_AGE) AS 'AVG_AGE_CONFIRMED'
FROM ALL_CONFIRMED;

/*11*/
/*以足跡來看匡列者*/
/*確診者案號、匡列人數*/
SELECT DISTINCT CASE_NUM, 
	   (SELECT COUNT(N_ID) FROM PEOPLE_FOOTPRINT WHERE PEOPLE_FOOTPRINT.F_DATE = CONFIRMED_FOOTPRINT.F_DATE
		AND PEOPLE_FOOTPRINT.PLACE_ID = CONFIRMED_FOOTPRINT.PLACE_ID) - 1 AS 'NUM_of_DANGER_PEOPLE'
FROM CONFIRMED_FOOTPRINT
WHERE (SELECT COUNT(DISTINCT N_ID) FROM PEOPLE_FOOTPRINT 
	   WHERE PEOPLE_FOOTPRINT.F_DATE = CONFIRMED_FOOTPRINT.F_DATE
	   AND PEOPLE_FOOTPRINT.PLACE_ID = CONFIRMED_FOOTPRINT.PLACE_ID) - 1 != '0'
ORDER BY CASE_NUM;

/*12*/
/*各縣市病床使用情況*/
/*各縣市的總治療醫院數、總病床數、總空病床數、占床率*/
SELECT CITY_NAME, COUNT(TREAT_HOSPITAL.MED_ID) AS 'TOTAL_TREAT_HOSPITAL', 
	   (SUM(HOS_TOTAL_WARD)) AS 'TOTAL_WARD',
	   (SUM(HOS_EMPTY_WARD)) AS 'TOTAL_EMPTY_WARD',
	   ROUND(CAST(((SUM(HOS_TOTAL_WARD)) - (SUM(HOS_EMPTY_WARD))) AS FLOAT) / 
	   CAST((SUM(HOS_TOTAL_WARD)) AS FLOAT) , 2) AS 'WARD_USERAGE'
FROM TREAT_HOSPITAL JOIN MEDICAL_INSTITUTION
ON TREAT_HOSPITAL.MED_ID = MEDICAL_INSTITUTION.MED_ID
JOIN AREA
ON AREA.AREA_NUM = MEDICAL_INSTITUTION.AREA_NUM
JOIN CITY
ON AREA.CITY_CODE = CITY.CITY_CODE
GROUP BY CITY_NAME;